# Generated by Django 5.1.5 on 2025-01-22 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('race', models.CharField(max_length=50)),
                ('character_class', models.CharField(max_length=50)),
                ('background', models.CharField(max_length=100)),
                ('alignment', models.CharField(max_length=50)),
                ('strength', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('constitution', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('wisdom', models.IntegerField()),
                ('charisma', models.IntegerField()),
                ('level', models.IntegerField(default=1)),
                ('experience_points', models.IntegerField(default=0)),
                ('hit_points', models.IntegerField()),
                ('armor_class', models.IntegerField()),
                ('initiative', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('acrobatics', models.BooleanField(default=False)),
                ('animal_handling', models.BooleanField(default=False)),
                ('arcana', models.BooleanField(default=False)),
                ('athletics', models.BooleanField(default=False)),
                ('deception', models.BooleanField(default=False)),
                ('history', models.BooleanField(default=False)),
                ('insight', models.BooleanField(default=False)),
                ('intimidation', models.BooleanField(default=False)),
                ('investigation', models.BooleanField(default=False)),
                ('medicine', models.BooleanField(default=False)),
                ('nature', models.BooleanField(default=False)),
                ('perception', models.BooleanField(default=False)),
                ('performance', models.BooleanField(default=False)),
                ('persuasion', models.BooleanField(default=False)),
                ('religion', models.BooleanField(default=False)),
                ('sleight_of_hand', models.BooleanField(default=False)),
                ('stealth', models.BooleanField(default=False)),
                ('survival', models.BooleanField(default=False)),
                ('proficiencies', models.TextField(blank=True)),
                ('equipment', models.TextField(blank=True)),
                ('spells', models.TextField(blank=True)),
                ('features_and_traits', models.TextField(blank=True)),
            ],
        ),
    ]
