# Generated by Django 5.1.5 on 2025-01-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solaris_app', '0004_remove_character_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.CharField(choices=[('Human', 'Humano'), ('Dwarf', 'Anão'), ('Elf', 'Elfo')], max_length=50, null=True),
        ),
    ]
